### ISSUE TITLE
[AddApp]: Type the title here...

### ISSUE THREAD

**Issue by jtutrow** [alpercun/fancy-macbook-app#10] opened 2023-01-31 21:19 UTC
The content of the application to be added

```json
{
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"; brew install --cask monitorcontrol meetingbar colorsnapper betterdisplay warp iina mos
}
```

**Comment by volkanto** [comment] 2023-02-01 10:08
duplicate of https://github.com/alpercun/fancy-macbook-app/issues/11 can be closed

**Closed** 2023-02-03 22:28 UTC
